name: primo_v2
description: Sistema POS con arquitectura hexagonal, BLoC y Drift
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.2

  get_it: ^7.6.4

  drift: ^2.13.2
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  dartz: ^0.10.1

  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0

  logger: ^2.0.2+1
  uuid: ^4.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  drift_dev: ^2.13.2
  build_runner: ^2.4.6

  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
